apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokedex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default
  source:
    repoURL: git@github.com:1600-services/app-pokedex-react-ci.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - prunePropagationPolicy=foreground
      - PruneLast=true
