---
apiVersion: v1
kind: Secret
metadata:
  name: app-pokedex-react-ci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:1600-services/app-pokedex-react-ci.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
                ********
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"